/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#111316',
        'background': '#111316',
        'surface-container-lowest': '#0c0e11',
        'surface-container-low': '#1a1c1f',
        'surface-container': '#1e2023',
        'surface-container-high': '#282a2d',
        'surface-container-highest': '#333538',
        'surface-variant': '#333538',
        'surface-bright': '#37393d',
        'surface-dim': '#111316',
        'surface-tint': '#ffba4b',
        'on-surface': '#e2e2e6',
        'on-surface-variant': '#d7c4ad',
        'on-background': '#e2e2e6',
        'primary': '#ffd59b',
        'primary-container': '#ffb020',
        'primary-fixed': '#ffddb1',
        'primary-fixed-dim': '#ffba4b',
        'on-primary': '#442b00',
        'on-primary-container': '#6b4600',
        'secondary': '#4ae176',
        'secondary-container': '#00b954',
        'secondary-fixed': '#6bff8f',
        'secondary-fixed-dim': '#4ae176',
        'on-secondary': '#003915',
        'on-secondary-container': '#004119',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'outline': '#9f8e79',
        'outline-variant': '#524533',
        'tertiary': '#ffd0cc',
        'tertiary-container': '#ffa9a3',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'sm': '0.125rem',
        'md': '0.25rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        '2xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-lg': '1rem',
        'space-xl': '1.5rem',
        'gutter': '0.75rem',
        'gutter-md': '1rem',
        'margin': '1rem',
        'margin-dock': '0.5rem',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-caps': ['0.625rem', { lineHeight: '0.875rem', letterSpacing: '0.08em', fontWeight: '600' }],
        'mono-sm': ['0.6875rem', { lineHeight: '1rem', letterSpacing: '0.02em', fontWeight: '500' }],
        'mono-md': ['0.8125rem', { lineHeight: '1.25rem', fontWeight: '400' }],
        'mono-lg': ['0.875rem', { lineHeight: '1.375rem', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-sm': ['0.8125rem', { lineHeight: '1.25rem', fontWeight: '400' }],
        'body-md': ['0.875rem', { lineHeight: '1.375rem', fontWeight: '400' }],
        'body-lg': ['0.9375rem', { lineHeight: '1.5rem', fontWeight: '400' }],
        'headline-sm': ['1rem', { lineHeight: '1.5rem', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['1.25rem', { lineHeight: '1.75rem', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-lg': ['1.75rem', { lineHeight: '2.25rem', letterSpacing: '-0.02em', fontWeight: '600' }],
      },
      animation: {
        'spin-slow': 'spin 8s linear infinite',
        'spin-reverse': 'spin 4s linear infinite reverse',
        'spin-fast': 'spin 2.5s linear infinite',
        'pulse-glow': 'pulseGlow 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        pulseGlow: {
          '0%, 100%': { opacity: '1', transform: 'scale(1)' },
          '50%': { opacity: '0.7', transform: 'scale(1.05)' },
        },
      },
    },
  },
  plugins: [],
}
