import asyncio
import contextlib
import json
from datetime import UTC, datetime
from typing import Any

from fastapi import APIRouter, Query, WebSocket, WebSocketDisconnect, status

from backend.app.config import get_settings
from backend.app.core.events import get_event_bus
from backend.app.core.exceptions import AuthenticationError
from backend.app.core.logging import get_logger
from backend.app.core.security import decode_jwt_token

logger = get_logger("websocket")
router = APIRouter(tags=["WebSocket Hub"])


def is_allowed_origin(origin: str | None, allowed_origins: list[str]) -> bool:
    """Validate whether the Origin header matches allowed localhost frontend origins."""
    if not origin:
        # Allow native non-browser clients (CLI tools, desktop scripts) where Origin header is absent
        return True

    # Strip trailing slashes for clean comparison
    normalized_origin = origin.rstrip("/")
    normalized_allowed = [o.rstrip("/") for o in allowed_origins]

    return normalized_origin in normalized_allowed


def authenticate_ws(
    websocket: WebSocket,
    token_param: str | None,
) -> dict[str, Any] | None:
    """
    Authenticate WebSocket client via cookie or query parameter token.
    Returns decoded token payload if valid, None if unauthenticated.
    """
    settings = get_settings()
    token = token_param or websocket.cookies.get("niko_access_token")
    if not token:
        return None

    try:
        payload = decode_jwt_token(
            token=token,
            secret_key=settings.JWT_SECRET_KEY,
            algorithm=settings.JWT_ALGORITHM,
        )
        return payload
    except AuthenticationError:
        return None


@router.websocket("/ws")
async def websocket_hub(
    websocket: WebSocket,
    token: str | None = Query(default=None),
) -> None:
    """
    Real-time bidirectional WebSocket Hub multiplexer.
    Streams pub/sub events (system metrics, chat chunks, approvals) from EventBus to client.
    Handles client heartbeat pings and topic subscriptions.
    """
    settings = get_settings()
    origin = websocket.headers.get("origin")

    # 1. Strict Origin Validation: prevent cross-site WebSocket hijacking (CSWSH)
    if not is_allowed_origin(origin, settings.WS_ALLOWED_ORIGINS):
        logger.warning("Rejected WebSocket connection with unauthorized origin", origin=origin)
        await websocket.close(
            code=status.WS_1008_POLICY_VIOLATION,
            reason="Forbidden: Origin not authorized to connect to local NIKO agent.",
        )
        return

    # 2. Authenticate client
    auth_payload = authenticate_ws(websocket, token)
    user_id = auth_payload.get("sub") if auth_payload else None

    await websocket.accept()
    logger.info("WebSocket connection established", user_id=user_id, origin=origin)

    # Subscribed topics for this connection (empty set means all topics)
    subscribed_topics: set[str] = set()
    event_bus = get_event_bus()
    active_chat_tasks: dict[str, asyncio.Task] = {}

    async def event_forwarder() -> None:
        """Stream events from EventBus out to the WebSocket client."""
        with contextlib.suppress(asyncio.CancelledError):
            try:
                async for event in event_bus.subscribe():
                    # Filter out events generated by this websocket connection to prevent duplicate echo
                    if isinstance(event.payload, dict) and event.payload.get("origin_ws_id") == id(websocket):
                        continue

                    # Filter by client subscription if client specified topic filters
                    compound_key = f"{event.topic}:{event.event_type}"
                    if subscribed_topics and event.topic not in subscribed_topics and compound_key not in subscribed_topics:
                        continue

                    msg = {
                        "type": compound_key,
                        "topic": event.topic,
                        "event_type": event.event_type,
                        "payload": event.payload,
                        "timestamp": event.timestamp.isoformat(),
                    }
                    await websocket.send_text(json.dumps(msg))
            except Exception as exc:
                logger.debug("Event forwarder stopped", error=str(exc))

    forwarder_task = asyncio.create_task(event_forwarder())

    async def _stream_chat_task(req_id: str, chat_data: dict[str, Any]) -> None:
        try:
            from sqlalchemy import select
            from backend.app.db.models import User
            from backend.app.db.session import get_session_maker
            from backend.app.services.chat_service import ChatService

            nonlocal user_id
            session_maker = get_session_maker()
            async with session_maker() as db:
                valid_user = False
                if user_id:
                    res = await db.execute(select(User.id).where(User.id == user_id))
                    valid_user = bool(res.scalar_one_or_none())
                if not valid_user:
                    res = await db.execute(select(User.id).where(User.role == "owner").limit(1))
                    user_id = res.scalar_one_or_none()
                if not user_id:
                    res = await db.execute(select(User.id).limit(1))
                    user_id = res.scalar_one_or_none()
                if not user_id:
                    default_owner = User(username="owner", password_hash="disabled", role="owner")
                    db.add(default_owner)
                    await db.flush()
                    user_id = default_owner.id

                conv_id = chat_data.get("conversation_id")
                content = chat_data.get("content") or chat_data.get("message") or ""
                source = chat_data.get("source")
                is_external = bool(chat_data.get("is_external", False))
                role = chat_data.get("role")
                elevated_mode = bool(chat_data.get("elevated_mode", False))

                chat_service = ChatService(db=db)
                async for ev in chat_service.stream_chat(
                    conversation_id=conv_id,
                    user_id=user_id,
                    user_message=content,
                    source=source,
                    is_external=is_external,
                    role=role,
                    elevated_mode=elevated_mode,
                ):
                    ev_type = ev.get("type")
                    if ev_type == "chunk":
                        payload = {
                            "type": "chat:chunk",
                            "request_id": req_id,
                            "conversation_id": conv_id,
                            "chunk": ev.get("content", ""),
                        }
                        await websocket.send_json(payload)
                        await event_bus.publish("chat", "chunk", {**payload, "origin_ws_id": id(websocket)})
                    elif ev_type == "tool_call":
                        payload = {
                            "type": "chat:tool_call",
                            "request_id": req_id,
                            "conversation_id": conv_id,
                            "name": ev.get("name"),
                            "arguments": ev.get("arguments", {}),
                            "tool_call_id": ev.get("tool_call_id"),
                        }
                        await websocket.send_json(payload)
                        await event_bus.publish("chat", "tool_call", {**payload, "origin_ws_id": id(websocket)})
                    elif ev_type == "tool_result":
                        payload = {
                            "type": "chat:tool_result",
                            "request_id": req_id,
                            "conversation_id": conv_id,
                            "name": ev.get("name"),
                            "result": ev.get("result"),
                            "error": ev.get("error"),
                            "status": ev.get("status"),
                            "tool_call_id": ev.get("tool_call_id"),
                        }
                        await websocket.send_json(payload)
                    elif ev_type == "approval_required":
                        payload = {
                            "type": "chat:approval_required",
                            "request_id": req_id,
                            "conversation_id": conv_id,
                            "approval": ev.get("approval"),
                        }
                        await websocket.send_json(payload)
                    elif ev_type == "done":
                        payload = {
                            "type": "chat:done",
                            "request_id": req_id,
                            "conversation_id": conv_id,
                            "response": ev.get("response"),
                        }
                        await websocket.send_json(payload)
                        await event_bus.publish("chat", "done", {**payload, "origin_ws_id": id(websocket)})
                await db.commit()
        except asyncio.CancelledError:
            logger.info("Chat streaming task cancelled", request_id=req_id)
            with contextlib.suppress(Exception):
                await websocket.send_json({"type": "chat:cancelled", "request_id": req_id})
            await event_bus.publish("chat", "cancelled", {"request_id": req_id, "origin_ws_id": id(websocket)})
        except Exception as e:
            logger.error("Error in chat streaming", error=str(e), request_id=req_id)
            with contextlib.suppress(Exception):
                await websocket.send_json({"type": "chat:error", "request_id": req_id, "error": str(e)})
        finally:
            active_chat_tasks.pop(req_id, None)

    try:
        while True:
            raw_text = await websocket.receive_text()
            try:
                data = json.loads(raw_text)
            except json.JSONDecodeError:
                await websocket.send_json({"type": "error", "message": "Invalid JSON format"})
                continue

            msg_type = data.get("type")

            if msg_type == "ping":
                await websocket.send_json(
                    {
                        "type": "pong",
                        "timestamp": data.get("timestamp") or datetime.now(UTC).isoformat(),
                    }
                )

            elif msg_type == "auth":
                # Late authentication via WS message
                client_token = data.get("token")
                if client_token:
                    try:
                        auth_payload = decode_jwt_token(
                            token=client_token,
                            secret_key=settings.JWT_SECRET_KEY,
                            algorithm=settings.JWT_ALGORITHM,
                        )
                        user_id = auth_payload.get("sub")
                        await websocket.send_json({"type": "auth_ok", "user_id": user_id})
                    except AuthenticationError as err:
                        await websocket.send_json({"type": "auth_error", "message": str(err)})
                else:
                    await websocket.send_json({"type": "auth_error", "message": "Missing token"})

            elif msg_type == "subscribe":
                # Update topic filter
                topics = data.get("topics")
                if isinstance(topics, list):
                    subscribed_topics = {str(t) for t in topics}
                    await websocket.send_json(
                        {
                            "type": "subscribed",
                            "topics": list(subscribed_topics),
                        }
                    )
                else:
                    await websocket.send_json(
                        {"type": "error", "message": "'topics' must be a list of topic names"}
                    )

            elif msg_type in ("chat", "chat:send"):
                import uuid
                req_id = data.get("request_id") or str(uuid.uuid4())
                task = asyncio.create_task(_stream_chat_task(req_id, data))
                active_chat_tasks[req_id] = task

            elif msg_type in ("cancel", "chat:cancel"):
                cancel_req_id = data.get("request_id")
                if cancel_req_id and cancel_req_id in active_chat_tasks:
                    active_chat_tasks[cancel_req_id].cancel()
                    await websocket.send_json({"type": "chat:cancel_ack", "request_id": cancel_req_id})
                elif active_chat_tasks:
                    for r_id, t in list(active_chat_tasks.items()):
                        t.cancel()
                    await websocket.send_json({"type": "chat:cancel_ack", "cancelled_all": True})
                else:
                    await websocket.send_json({"type": "chat:cancel_ack", "status": "none_active"})

            else:
                await websocket.send_json(
                    {
                        "type": "ack",
                        "received": msg_type,
                    }
                )

    except WebSocketDisconnect:
        logger.info("WebSocket client disconnected", user_id=user_id)
    except Exception as exc:
        logger.warning("WebSocket exception terminated connection", error=str(exc))
    finally:
        for t in list(active_chat_tasks.values()):
            t.cancel()
        forwarder_task.cancel()
        with contextlib.suppress(asyncio.CancelledError):
            await forwarder_task
