/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Setup Initial Owner
         * @description One-time initial boot setup barrier.
         *     Requires the secret SETUP_TOKEN from server logs / .env.
         *     Once any owner exists, this endpoint is permanently disabled.
         */
        post: operations["setup_initial_owner_api_v1_auth_setup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Owner login with username-keyed rate limiting and exponential backoff.
         *     Sets httpOnly session cookies.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Tokens
         * @description Rotate session refresh token with automatic reuse detection.
         */
        post: operations["refresh_tokens_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke current session and clear cookies.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Return currently authenticated user profile.
         */
        get: operations["get_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Pending Approvals
         * @description List all pending tool approvals that have not yet expired.
         */
        get: operations["list_pending_approvals_api_v1_approvals_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/{approval_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Approval Details
         * @description Retrieve details for a specific approval request.
         */
        get: operations["get_approval_details_api_v1_approvals__approval_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/{approval_id}/respond": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Respond To Approval
         * @description Approve or deny a pending tool call.
         *     Validates single-use transition, unexpired TTL, and cryptographic arguments hash integrity.
         */
        post: operations["respond_to_approval_api_v1_approvals__approval_id__respond_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Skills
         * @description List all available skills enriched with their database autonomy settings.
         */
        get: operations["list_skills_api_v1_skills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skills/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Skill Config
         * @description Update owner autonomy policy, timeout, or enabled flag for a skill.
         *     Stored persistently in the database, allowing full user customization without hardcoded locks.
         */
        patch: operations["update_skill_config_api_v1_skills__name__patch"];
        trace?: never;
    };
    "/api/v1/skills/{name}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute Skill
         * @description Execute a skill with guard validation, provenance tracking, and audit logging.
         */
        post: operations["execute_skill_api_v1_skills__name__execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skills/undo/{undo_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Pending Undo
         * @description Cancel a skill execution during its active 5-second undo delay window.
         */
        post: operations["cancel_pending_undo_api_v1_skills_undo__undo_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current Metrics
         * @description Get an immediate live snapshot of host CPU, RAM, disk, and battery.
         */
        get: operations["get_current_metrics_api_v1_metrics_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Metrics History
         * @description Retrieve 1-minute historical telemetry aggregates.
         */
        get: operations["get_metrics_history_api_v1_metrics_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/visibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update Tab Visibility
         * @description Adjust telemetry streaming cadence dynamically based on client tab visibility.
         *     Active tab streams every 2 seconds; backgrounded tab throttles to 15 seconds.
         */
        post: operations["update_tab_visibility_api_v1_metrics_visibility_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Model Roles
         * @description Retrieve the current ordered model roles configuration.
         */
        get: operations["get_model_roles_api_v1_settings_roles_get"];
        /**
         * Update Model Roles
         * @description Update the ordered model roles configuration.
         *     Stored in the settings table and used by the LLM orchestrator.
         */
        put: operations["update_model_roles_api_v1_settings_roles_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/models/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Models
         * @description Admin refresh: queries live endpoints for Gemini, Groq, and OpenRouter
         *     to discover active available models and filter for free tool-capable models.
         */
        post: operations["refresh_models_api_v1_settings_models_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/models/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Models Status
         * @description Return predictive cooldown and rate-limit consumption status.
         */
        get: operations["get_models_status_api_v1_settings_models_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApprovalDecisionRequest */
        ApprovalDecisionRequest: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "approve" | "deny";
            /**
             * Arguments
             * @description Optional current arguments to cryptographically verify against original args_hash
             */
            arguments?: {
                [key: string]: unknown;
            } | null;
        };
        /** ApprovalResponse */
        ApprovalResponse: {
            /** Id */
            id: string;
            /** Tool Call Id */
            tool_call_id: string;
            /** Skill Name */
            skill_name?: string | null;
            /** Arguments */
            arguments?: {
                [key: string]: unknown;
            } | null;
            /** Args Hash */
            args_hash: string;
            /** Status */
            status: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Decided At */
            decided_at?: string | null;
            /** Decided By */
            decided_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AuthResponse */
        AuthResponse: {
            /** Message */
            message: string;
            /** User Id */
            user_id: string;
            /** Username */
            username: string;
            /** Role */
            role: string;
            /** Access Token */
            access_token: string;
        };
        /** CurrentMetricsResponse */
        CurrentMetricsResponse: {
            /** Cpu Percent */
            cpu_percent: number;
            /** Ram Percent */
            ram_percent: number;
            /** Disk Percent */
            disk_percent: number;
            /** Battery Percent */
            battery_percent?: number | null;
            /** Timestamp */
            timestamp: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @example healthy
             */
            status: string;
            /**
             * Version
             * @example 0.1.0
             */
            version: string;
            /** Uptime Seconds */
            uptime_seconds: number;
            /** Request Id */
            request_id: string;
            /**
             * Database
             * @example connected
             */
            database: string;
            /** Storage */
            storage: {
                [key: string]: unknown;
            };
        };
        /** HistoricalMetricPoint */
        HistoricalMetricPoint: {
            /** Id */
            id: string;
            /** Cpu Percent */
            cpu_percent: number;
            /** Ram Percent */
            ram_percent: number;
            /** Disk Percent */
            disk_percent: number;
            /** Battery Percent */
            battery_percent?: number | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Username
             * @description User username
             */
            username: string;
            /**
             * Password
             * @description User password
             */
            password: string;
        };
        /** ModelRolesConfig */
        ModelRolesConfig: {
            /** Light */
            light?: components["schemas"]["RoleModelTarget"][];
            /** Chat */
            chat?: components["schemas"]["RoleModelTarget"][];
            /** Code */
            code?: components["schemas"]["RoleModelTarget"][];
            /** Search */
            search?: components["schemas"]["RoleModelTarget"][];
        };
        /** RoleModelTarget */
        RoleModelTarget: {
            /**
             * Provider
             * @description Provider name: gemini, groq, openrouter
             */
            provider: string;
            /**
             * Model
             * @description Exact model ID
             */
            model: string;
            /**
             * Max Output Tokens
             * @default 2048
             */
            max_output_tokens: number;
            /**
             * Reasoning Effort
             * @description low or default
             * @default default
             */
            reasoning_effort: string;
            /**
             * Temperature
             * @default 0.7
             */
            temperature: number;
        };
        /** SetupRequest */
        SetupRequest: {
            /**
             * Username
             * @description Owner username
             */
            username: string;
            /**
             * Password
             * @description Owner password
             */
            password: string;
            /**
             * Setup Token
             * @description One-time setup token (can also be passed via X-Setup-Token header)
             */
            setup_token?: string | null;
        };
        /** SetupResponse */
        SetupResponse: {
            /** Message */
            message: string;
            /** User Id */
            user_id: string;
            /** Username */
            username: string;
            /** Role */
            role: string;
            /** Providers Initialized */
            providers_initialized: string[];
        };
        /** SkillExecutePayload */
        SkillExecutePayload: {
            /**
             * Arguments
             * @description Skill execution input parameters
             */
            arguments?: {
                [key: string]: unknown;
            };
            /**
             * Elevated Mode
             * @description Whether elevated execution mode is enabled
             * @default false
             */
            elevated_mode: boolean;
        };
        /** SkillExecuteResponse */
        SkillExecuteResponse: {
            /** Success */
            success: boolean;
            /** Data */
            data?: unknown;
            /** Error */
            error?: string | null;
            /**
             * Execution Time Ms
             * @default 0
             */
            execution_time_ms: number;
        };
        /** SkillResponse */
        SkillResponse: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Default Tier */
            default_tier: string;
            /** Autonomy Policy */
            autonomy_policy: string;
            /** Enabled */
            enabled: boolean;
            /** Timeout Seconds */
            timeout_seconds: number;
            /** Parameters Schema */
            parameters_schema: {
                [key: string]: unknown;
            };
        };
        /** SkillUpdatePayload */
        SkillUpdatePayload: {
            /**
             * Autonomy Policy
             * @description Autonomy mode: 'ask' (always prompt), 'auto' (run freely), 'auto+log' (run with audit toast)
             */
            autonomy_policy?: ("ask" | "auto" | "auto+log") | null;
            /**
             * Enabled
             * @description Whether the skill is active
             */
            enabled?: boolean | null;
            /**
             * Timeout Seconds
             * @description Max execution timeout in seconds
             */
            timeout_seconds?: number | null;
        };
        /** TabVisibilityPayload */
        TabVisibilityPayload: {
            /**
             * Hidden
             * @description Whether the client browser tab is hidden (drops polling to 15s) or visible (restores 2s cadence)
             */
            hidden: boolean;
        };
        /** UndoCancelResponse */
        UndoCancelResponse: {
            /** Undo Id */
            undo_id: string;
            /** Cancelled */
            cancelled: boolean;
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            /** Role */
            role: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VisibilityResponse */
        VisibilityResponse: {
            /** Hidden */
            hidden: boolean;
            /** Interval Seconds */
            interval_seconds: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    setup_initial_owner_api_v1_auth_setup_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Setup-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_tokens_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                niko_refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                niko_refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                niko_access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pending_approvals_api_v1_approvals_pending_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                niko_access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_approval_details_api_v1_approvals__approval_id__get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path: {
                approval_id: string;
            };
            cookie?: {
                niko_access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    respond_to_approval_api_v1_approvals__approval_id__respond_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path: {
                approval_id: string;
            };
            cookie?: {
                niko_access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_skills_api_v1_skills_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                niko_access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_skill_config_api_v1_skills__name__patch: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path: {
                /** @description Skill name identifier */
                name: string;
            };
            cookie?: {
                niko_access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillUpdatePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_skill_api_v1_skills__name__execute_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path: {
                /** @description Skill name identifier */
                name: string;
            };
            cookie?: {
                niko_access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillExecutePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillExecuteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_pending_undo_api_v1_skills_undo__undo_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path: {
                /** @description The unique undo operation identifier */
                undo_id: string;
            };
            cookie?: {
                niko_access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UndoCancelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_metrics_api_v1_metrics_current_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                niko_access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentMetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metrics_history_api_v1_metrics_history_get: {
        parameters: {
            query?: {
                /** @description Max historical records to retrieve */
                limit?: number;
            };
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                niko_access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoricalMetricPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_tab_visibility_api_v1_metrics_visibility_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                niko_access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TabVisibilityPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisibilityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_model_roles_api_v1_settings_roles_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                niko_access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelRolesConfig"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_model_roles_api_v1_settings_roles_put: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                niko_access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelRolesConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelRolesConfig"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_models_api_v1_settings_models_refresh_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                niko_access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_models_status_api_v1_settings_models_status_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                niko_access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
