from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class ModelRole(StrEnum):
    LIGHT = "light"
    CHAT = "chat"
    CODE = "code"
    SEARCH = "search"


class RoleModelTarget(BaseModel):
    model_config = ConfigDict(extra="ignore")

    provider: str = Field(..., description="Provider name: gemini, groq, openrouter")
    model: str = Field(..., description="Exact model ID")
    max_output_tokens: int = Field(default=2048, ge=64, le=65536)
    reasoning_effort: str = Field(default="default", description="low or default")
    temperature: float = Field(default=0.7, ge=0.0, le=2.0)


class ModelRolesConfig(BaseModel):
    model_config = ConfigDict(extra="ignore")

    light: list[RoleModelTarget] = Field(default_factory=list)
    chat: list[RoleModelTarget] = Field(default_factory=list)
    code: list[RoleModelTarget] = Field(default_factory=list)
    search: list[RoleModelTarget] = Field(default_factory=list)

    def get_role_targets(self, role: ModelRole | str) -> list[RoleModelTarget]:
        role_str = role.value if isinstance(role, ModelRole) else str(role).lower()
        role_map = {
            "light": self.light,
            "chat": self.chat,
            "code": self.code,
            "search": self.search,
        }
        return role_map.get(role_str, self.chat)


class NormalizedToolCall(BaseModel):
    model_config = ConfigDict(extra="ignore")

    id: str = Field(default="", description="Unique tool call invocation ID")
    name: str = Field(..., description="Name of the skill/tool")
    arguments: dict[str, Any] = Field(default_factory=dict, description="Parsed arguments dict")


class LLMMessage(BaseModel):
    model_config = ConfigDict(extra="ignore")

    role: str = Field(..., description="Role: system, user, assistant, tool")
    content: str = Field(default="", description="Text content")
    tool_calls: list[NormalizedToolCall] | None = Field(
        default=None, description="Tool calls generated by assistant"
    )
    tool_call_id: str | None = Field(
        default=None, description="Tool call ID for tool role results"
    )
    name: str | None = Field(
        default=None, description="Name of the tool/function for tool role messages"
    )


class StreamChunk(BaseModel):
    model_config = ConfigDict(extra="ignore")

    content: str = Field(default="", description="Delta text token chunk")
    tool_calls: list[NormalizedToolCall] | None = Field(
        default=None, description="Delta or complete tool call chunks"
    )
    finish_reason: str | None = Field(default=None)
    usage: dict[str, int] | None = Field(default=None)


class LLMResponse(BaseModel):
    model_config = ConfigDict(extra="ignore")

    content: str = Field(default="")
    tool_calls: list[NormalizedToolCall] = Field(default_factory=list)
    model_used: str = Field(...)
    provider_used: str = Field(...)
    input_tokens: int = Field(default=0)
    output_tokens: int = Field(default=0)
    finish_reason: str = Field(default="stop")


class ProviderRateLimit(BaseModel):
    model_config = ConfigDict(extra="ignore")

    rpm: int = Field(..., description="Requests per minute")
    rpd: int = Field(..., description="Requests per day")
    tpm: int = Field(..., description="Tokens per minute")
    tpd: int = Field(default=0, description="Tokens per day (0 if uncapped/unverified)")
    source: str = Field(...)
